version: "2"
services:
  knovator-app10:
    container_name: knovator-app10
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - 80:80
    environment:
      NODE_ENV: production